about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new_post, name='new_post'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('follow/', views.follow_index, name='follow_index'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path('<str:username>/<int:post_id>/edit/', views.post_edit,
         name='post_edit'),
    path("<username>/<int:post_id>/comment/", views.add_comment,
         name='add_comment'),
    path('<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path("<str:username>/unfollow/", views.profile_unfollow,
         name='profile_unfollow')

]

yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404, handler500
from posts import views
from django.conf import settings
from django.conf.urls.static import static

handler500 = 'posts.views.server_error'  # noqa
handler404 = 'posts.views.page_not_found'  # noqa

urlpatterns = [
    path('admin/', admin.site.urls),
    path('404/', views.page_not_found, name='404'),
    path('500/', views.server_error, name='500'),
    path('', include('posts.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        verbose_name='Название группы',
        max_length=200,
        help_text='Придумайте название для группы',
        unique=True
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Здесь расскажите про что ваша группа'
    )
    slug = models.SlugField(
        verbose_name='Слаг',
        help_text=('Укажите адрес для страницы группы. Используйте только'
                   ' латиницу, цифры, дефисы и знаки подчеркивания'),
        unique=True,
        blank=True,
        max_length=100

    )

    def __str__(self):
        return self.title[:15]

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.title[:100]
        super().save(*args, **kwargs)


class Post(models.Model):
    text = models.TextField(verbose_name='Текст',
                            help_text='Напишите здесь что-либо'
                            )
    pub_date = models.DateTimeField(verbose_name='Дата публикации',
                                    help_text=('Дата публикации. Добавляется'
                                               ' автоматически'),
                                    auto_now_add=True,
                                    db_index=True
                                    )
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts',
                               verbose_name='Автор',
                               help_text=('Здесь необходимо выбрать автора'
                                          ' публикации')
                               )
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True,
                              null=True, related_name='posts',
                              verbose_name='Группа',
                              help_text=('Здесь можно выбрать группу для '
                                         'публикации')
                              )
    image = models.ImageField(upload_to='posts/', blank=True, null=True)

    def __str__(self):
        return self.text[:15]

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'
        ordering = ['-pub_date'][:12]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='comments')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='follower')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='following')

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='user_follow')]

posts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': _('Текст:'),
            'group': _('Выберете группу:')
        }
        help_texts = {
            'text': _('В верхнее поле можно написать текст')
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': _('Текст')}
        help_texts = {'text': _('Напишите здесь комментарий')}
        widgets = {
            'text': forms.Textarea(attrs={'cols': 60, 'rows': 6})
        }

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from posts.models import Post, Group, Follow
from posts.forms import PostForm, CommentForm
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()


def index(request):
    latest = Post.objects.all()
    paginator = Paginator(latest, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'posts/index.html', {'page': page})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'posts/group.html', {'group': group, 'page': page})


@login_required
def new_post(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:index')
    return render(request, 'posts/new.html', {'form': form})


@login_required
def add_comment(request, username, post_id):
    author = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, author=author, id=post_id)
    form = CommentForm(request.POST or None)
    reverse_kwargs = {'username': username, 'post_id': post_id}
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect(reverse('posts:post', kwargs=reverse_kwargs))


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts_by_author = author.posts.filter(author=author)
    paginator = Paginator(posts_by_author, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    if request.user.is_authenticated:
        authors = User.objects.filter(following__user=request.user)
        following = author in authors
        return render(request, 'posts/profile.html', {'author': author,
                                                      'page': page,
                                                      'following': following})
    return render(request, 'posts/profile.html', {'author': author,
                                                  'page': page})


def post_view(request, username, post_id):
    author = get_object_or_404(User, username=username)
    posts_by_id = get_object_or_404(Post, author=author, id=post_id)
    form = CommentForm()
    comments = posts_by_id.comments.all()
    return render(request, 'posts/post.html', {'author': author,
                                               'post': posts_by_id,
                                               'form': form,
                                               'comments': comments})


@login_required
def post_edit(request, username, post_id):
    username = get_object_or_404(User, username=username)
    if request.user == username:
        post = get_object_or_404(Post, author=username, id=post_id)
        form = PostForm(request.POST or None,
                        files=request.FILES or None,
                        instance=post)
        if request.method == 'POST' and form.is_valid():
            form.save()
            return redirect(reverse('posts:post', kwargs={'username': username,
                                                          'post_id': post_id}))
        return render(request, 'posts/new.html', {'form': form,
                                                  'here': True,
                                                  'post': post})
    return redirect(reverse('posts:post', kwargs={'username': username,
                                                  'post_id': post_id}))


def page_not_found(request, exception):
    return render(request, 'misc/404.html', {'path': request.path}, status=404)


def server_error(request):
    return render(request, 'misc/500.html', status=500)


@login_required
def follow_index(request):
    user = request.user
    posts = Post.objects.filter(author__following__user=user)
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    return render(request, "follow.html", {'page': page})


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect(reverse('posts:profile', args=[username]))


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(user=user, author=author)
    follow.delete()
    return redirect(reverse('posts:profile', args=[username]))

templates/posts/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
    <form method="post" action= {% url 'posts:add_comment' username=post.author.username post_id=post.id  %} >
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

<!-- Комментарии -->
{% for item in post.comments.all %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'posts:profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %}

templates/posts/follow.html
{% extends "base.html" %}
{% block title %} Подписки{% endblock %}

{% load cache %}
{% cache 20 follow_page  %}
{% block content %}

    <div class="container">

        {% include 'posts/menu.html' %}
           <h1> Последние новости от друзей</h1>
            <!-- Вывод ленты записей -->
                {% for post in page %}
                  <!-- Вот он, новый include! -->
                    {% include "post_item.html" with post=post %}
                {% endfor %}
    </div>

        <!-- Вывод паджинатора -->
        {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator%}
        {% endif %}



{% endblock %}
{% endcache %}

templates/posts/group.html
{% extends "base.html" %}
{% block title %} Записи сообщества {{ group.title }} {% endblock %}
{% block header %} {{ group.title }} {% endblock %}
{% block content %}
 <p> {{ group.description }} </p>
    {% for post in page %}
        {% include 'posts/post_item.html' %}


                    {% endfor %}
                {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator%}
        {% endif %}

     </div>
    </div>
</main>

{% endblock %}

templates/posts/index.html
{% extends "base.html" %}
{% block title %} Последние обновления {% endblock %}


{% block content %}

    <div class="container">

        {% include 'posts/menu.html' %}

            <h1> Последние обновления на сайте</h1>
            <!-- Вывод ленты записей -->
                {% load cache %}
                {% cache 20 index_page request.user.username page.number %}
                {% for post in page %}
                  <!-- Вот он, новый include! -->
                    {% include "post_item.html" with post=post %}
                {% endfor %}
                {% endcache %}
    </div>

        <!-- Вывод паджинатора -->
        {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator%}
        {% endif %}



{% endblock %}

templates/posts/menu.html
{% if user.is_authenticated %}
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'posts:index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="/follow">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %}

templates/posts/new.html
{% extends "base.html" %}
{% block title %}Добавить запись{% endblock %}
{% block header %} {% endblock %}
{% load user_filters %}
{% block content %}
{% if here is True %}
    <h1>Отредактируйте вашу запись </h1>
    {% else %}
<h1>Добавьте вашу запись </h1>
    {% endif %}
<p>{{ author }}</p>
<div>
{% if here is True %}
    <form method="post" enctype="multipart/form-data">
{% else %}
<form method="post" enctype="multipart/form-data" action="{% url 'posts:new_post' %}">
    {% endif %}
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required"></span>{% endif %}</label>
                                <div class="col-md-6">

                                    {# подключаем фильтр и указываем класс #}
                                    {{ field|addclass:"form-control" }}

                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>

                    {% endfor %}

                    <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {% if here is True %}
                                Редактировать запись
                                {% else %}
                                Опубликовать запись
                                {% endif %}
                            </button>
                    </div>
        </form>



{% endblock %}

templates/posts/post.html
{% extends "base.html" %}
{% block title %}Запись{% endblock %}


    {% block content %}
    {% include 'posts/post_item.html' with post=post %}
        {% include 'posts/comments.html' %}

    {% endblock %}

templates/posts/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

  <!-- Отображение картинки -->
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img" src="{{ im.url }}" />
  {% endthumbnail %}
  <!-- Отображение текста поста -->
  <div class="card-body">
    <p class="card-text">
      <!-- Ссылка на автора через @ -->
      <a name="post_{{ post.id }}" href="{% url 'posts:profile' post.author.username %}">
        <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
      </a>
      {{ post.text|linebreaksbr }}
    </p>

    <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
    {% if post.group %}
    <a class="card-link muted" href="{% url 'posts:group' post.group.slug %}">
      <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
    </a>
    {% endif %}

    <!-- Отображение ссылки на комментарии -->
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        {% if post.comments.exists %}
        <div>
          Комментариев: {{ post.comments.count }}
        </div>
        {% endif %}

        <a class="btn btn-sm btn-primary" href="{% url 'posts:post' post.author.username post.id %}" role="button">
          Добавить комментарий
        </a>
          <!-- Ссылка на редактирование поста для автора -->
        {% if user == post.author %}
        <a class="btn btn-sm btn-info" href="{% url 'posts:post_edit' post.author.username post.id %}" role="button">
          Редактировать
        </a>
        {% endif %}

      </div>

      <!-- Дата публикации поста -->
      <small class="text-muted">{{ post.pub_date }}</small>
    </div>
  </div>
</div>

templates/posts/profile.html
{% extends "base.html" %}
{% block title %} Записи пользователя {{ author }}  {% endblock %}



    {% block content %}

    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                    <div class="card">
                            <div class="card-body">
                                    <div class="h2">
                                        {{ author.get_full_name }}
                                    </div>
                                    <div class="h3 text-muted">
                                         <!-- username автора -->
                                         {{ author }}
                                    </div>
                            </div>
                            <ul class="list-group list-group-flush">
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                            Подписчиков: {{ author.following.count }} <br />
                                            Подписан: {{ author.follower.count }}
                                            </div>
                                    </li>
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                                <!-- Количество записей -->
                                                Записей: {{ page.paginator.count }}
                                            </div>
                                    </li>
                                <li class="list-group-item">

                                    {% if following %}
                                        <a class="btn btn-lg btn-light"
                                            href="{% url 'posts:profile_unfollow' author.username %}" role="button">
                                                Отписаться
                                        </a>
                                    {% else %}
                                        <a class="btn btn-lg btn-primary"
                                            href="{% url 'posts:profile_follow' author.username %}" role="button">
                                                Подписаться
                                        </a>
                                    {% endif %}


                                </li>
                            </ul>
                    </div>
            </div>


            <div class="col-md-9">

                <!-- Начало блока с отдельным постом -->

                    {% for post in page %}
                        {% include 'posts/post_item.html' %}
                    {% endfor %}
                <!-- Конец блока с отдельным постом -->

                <!-- Остальные посты -->

                <!-- Здесь постраничная навигация паджинатора -->
                {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator%}
                {% endif %}

     </div>
    </div>
</main>

{% endblock %}